services:
  le-grimoire:
    build:
      context: .
      dockerfile: Dockerfile
    image: priyanshu9943/le-grimoire:latest
    container_name: le-grimoire
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - CHROME_REMOTE_URL=${CHROME_REMOTE_URL}
      - KAVITA_BASE_URL=${KAVITA_BASE_URL}
      - KAVITA_API_KEY=${KAVITA_API_KEY}
      # - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      # - SERVER_PORT=${SERVER_PORT:-8321}
    ports:
      - "8321:8321"
    volumes:
      - ./.config:/home/appuser/.config/le-grimoire
    depends_on:
      - headless-shell
      - kavita
    networks:
      - media_net

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      # The following volumes are mounted to the host machine's MEDIA_DIR directory.
      # You can change the MEDIA_DIR environment variable in your .env file to point
      # to a different location on your host machine.
      - ${MEDIA_DIR}/manga:/manga
      - ${MEDIA_DIR}/comics:/comics
      - ${MEDIA_DIR}/books:/books
      - ${MEDIA_DIR}/lightnovels:/lightnovels
      - ${MEDIA_DIR}/.config/kavita:/kavita/config     # /kavita/config must not be changed
    environment:
      - TZ=Asia/Kolkata
    expose:
      - "5000"
    # ports:
    #   - "5000:5000"
    restart: unless-stopped
    networks:
      - media_net

  headless-shell:
    image: chromedp/headless-shell:latest
    container_name: headless-shell
    restart: unless-stopped
    init: true # Required for proper chromedp zombie process cleanup
    shm_size: 2gb # Crucial: prevents Chrome crashes under memory load
    command:
      - --remote-allow-origins=*
      - --disable-gpu
      - --no-sandbox
      - --disable-web-security
      - --allow-running-insecure-content
      - --disable-features=IsolateOrigins,site-per-process,BlockInsecurePrivateNetworkRequests
    expose:
      - "9222"
    # Exposes the remote debugging port to the host machine for external access
    # ports:
    #   - "9223:9222"
    environment:
      - TZ=Asia/Kolkata
    networks:
      - media_net

networks:
  media_net:
    driver: bridge
