package kavita

import (
	"bytes"
	"fmt"
	"le-grimoire/internal/library"
	"net/url"
	"sort"
	"strconv"
	"strings"
)

func mapKavitaLibraryToLibrary(raw kavitaLibrary) library.Library {
	return library.Library{
		ID:   strconv.Itoa(raw.ID),
		Name: raw.Name,
	}
}

func mapLibraryListToLibraries(raw []kavitaLibrary) []library.Library {
	libraries := make([]library.Library, len(raw))
	for i, r := range raw {
		libraries[i] = mapKavitaLibraryToLibrary(r)
	}
	return libraries
}

func mapSeriesToBook(s kavitaSeries) library.Book {
	return library.Book{
		ID:        strconv.Itoa(s.ID),
		LibraryID: strconv.Itoa(s.LibraryID),
		Title:     s.Name,
		Author:    "",                 // Kavita's series list doesn't include author; comes from SeriesDetail
		CoverID:   strconv.Itoa(s.ID), // resolved later via a Cover() call using the same series ID
		Format:    mangaFormat(s.Format).toDomain(),
	}
}

func mapSeriesListToBooks(list []kavitaSeries) []library.Book {
	books := make([]library.Book, 0, len(list))
	for _, s := range list {
		books = append(books, mapSeriesToBook(s))
	}
	return books
}

func mapChapter(seriesID string, c kavitaChapter) library.Chapter {
	num, err := strconv.ParseFloat(c.Number, 64)
	if err != nil {
		num = 0 // fallback for non-numeric chapter labels ("Special", etc.)
	}
	return library.Chapter{
		ID:     strconv.Itoa(c.ID),
		BookID: seriesID,
		Number: num,
		Title:  c.Title,
	}
}

func mapChapterInfo(raw *chapterInfoResponse) *library.ChapterInfo {
	return &library.ChapterInfo{
		ChapterID:  strconv.Itoa(raw.ChapterID),
		TotalPages: raw.Pages,
		Format:     mangaFormat(raw.SeriesFormat).toDomain(),
	}
}

// flattenVolumes walks volumes in order and collects their chapters,
// producing a single reading-order list
func flattenVolumes(seriesID string, volumes []kavitaVolume) []library.Chapter {
	var chapters []library.Chapter
	for _, v := range volumes {
		for _, c := range v.Chapters {
			newChapter := mapChapter(seriesID, c)
			// Format Chapter Titles: Kavita's chapter titles can be empty or just
			// whitespace, so we need to generate a fallback title based on the
			// chapter number or index.
			newChapter.Title = formatChapterTitle(c, len(chapters))
			chapters = append(chapters, newChapter)
		}
	}

	// Kavita doesn't guarantee cross-volume chapter ordering in the raw
	// response, so sort explicitly by Number to be safe.
	sort.Slice(chapters, func(i, j int) bool {
		return chapters[i].Number < chapters[j].Number
	})
	return chapters
}

func formatChapterTitle(c kavitaChapter, fallbackIndex int) string {
	if strings.TrimSpace(c.Title) != "" {
		return c.Title
	}

	// Handle Kavita's -100000 sentinel or specials
	if c.IsSpecial || strings.HasPrefix(c.Number, "-100000") {
		if c.Title != "" {
			return c.Title
		}
		return fmt.Sprintf("Special / Extra %d", fallbackIndex+1)
	}

	// Fallback for unnumbered single-file books / chapters
	if c.Number == "" || c.Number == "0" {
		return fmt.Sprintf("Entry %d", fallbackIndex+1)
	}

	return fmt.Sprintf("Chapter %s", c.Number)
}

// fixes protocol-relative resource URLs generated by Kavita
func sanitizeEPUBHTML(chapterHTML []byte, baseURL string) []byte {
	parsedBase, err := url.Parse(baseURL)
	scheme := "http:"
	if err == nil && parsedBase.Scheme != "" {
		scheme = parsedBase.Scheme + ":"
	}

	cleanHostPath := strings.TrimPrefix(baseURL, "http:")
	cleanHostPath = strings.TrimPrefix(cleanHostPath, "https:")

	if strings.HasPrefix(cleanHostPath, "//") {
		// Convert only the small search/replace strings to bytes
		oldPath := []byte(cleanHostPath)
		newPath := []byte(scheme + cleanHostPath)
		chapterHTML = bytes.ReplaceAll(chapterHTML, oldPath, newPath)
	}

	// Pre-compile the byte slices for replacement to avoid inline fmt.Sprintf allocations
	srcDoubleOld := []byte(`src="//`)
	srcDoubleNew := []byte(`src="` + scheme + `//`)
	chapterHTML = bytes.ReplaceAll(chapterHTML, srcDoubleOld, srcDoubleNew)

	srcSingleOld := []byte(`src='//`)
	srcSingleNew := []byte(`src='` + scheme + `//`)
	chapterHTML = bytes.ReplaceAll(chapterHTML, srcSingleOld, srcSingleNew)

	hrefDoubleOld := []byte(`href="//`)
	hrefDoubleNew := []byte(`href="` + scheme + `//`)
	chapterHTML = bytes.ReplaceAll(chapterHTML, hrefDoubleOld, hrefDoubleNew)

	hrefSingleOld := []byte(`href='//`)
	hrefSingleNew := []byte(`href='` + scheme + `//`)
	chapterHTML = bytes.ReplaceAll(chapterHTML, hrefSingleOld, hrefSingleNew)

	return chapterHTML
}

type chapterInfoResponse struct {
	ChapterID    int `json:"chapterId"`
	SeriesFormat int `json:"seriesFormat"`
	Pages        int `json:"pages"`
}
