@baseUrl = http://localhost:8321
@baseAPIv1Url = {{baseUrl}}/api/v1
@deviceId = esp32-test-device-01
@apiKey = test-key


### Health Check 
GET {{baseUrl}}/health


### Get Current Page
GET {{baseAPIv1Url}}/current_page
X-Device-Id: {{deviceId}}
Authorization: Bearer {{apiKey}}

### Push Button
POST {{baseAPIv1Url}}/push_button
X-Device-Id: {{deviceId}}
Authorization: Bearer {{apiKey}}

{
    "button_id": "A",
    "type": "short_press"
}

### Long Button press
POST {{baseAPIv1Url}}/push_button
X-Device-Id: {{deviceId}}
Authorization: Bearer {{apiKey}}

{
    "button_id": "E",
    "type": "long_press"
}
